### ISSUE TITLE
Open graph data not being picked up

### ISSUE THREAD

**Issue by adamalston** [staylor/react-helmet-async#105]
I am checking open graph data for a site that I am currently working on using 2 tools:
- https://www.opengraph.xyz/
- https://smallseotools.com/open-graph/

Neither site picks up the data I have passed through the meta tags via `react-helmet-async`

```js
<HelmetProvider>
    <Helmet>
        <title>test0</title>

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="000000" />
        <meta name="author" content="test1" />
        <meta name="keywords" content="test1" />

        <meta name="title" property="og:title" content="test2" />
        <meta name="description" property="og:description" content="test2" />

        <meta property="og:site_name" content="test3" />
        <meta property="og:url" content="" />
        <meta property="og:locale" content="en_US" />
        <meta property="og:image" content="https://bit.ly/2FvZpEH" />
        <meta property="og:image:type" content="image/png" />
        <meta property="og:image:width" content="1280" />
        <meta property="og:image:height" content="640" />
        <meta property="og:image:alt" content="test4" />
        <meta property="og:type" content="website" />
    </Helmet>
</HelmetProvider>
```

None of this data appears in either of the open graph tools. When I put this same data in a static `index.html` file however, the tools pick it up just fine.

I am building the site using Create React App. When I run the dev environment locally, the information is successfully passed to the head of the document: 

<img width="549" alt="image" src="https://user-images.githubusercontent.com/18297826/93029378-8624d500-f5e8-11ea-817c-5d644db901f9.png">

It's only after building and staging the deployment that the data is either not there or not recognized.

**Comment by acomito** [comment]
@adamalston Did you solve this? I was considering using this with CRA as well.

**Comment by adamalston** [comment]
@acomito I did not. No one answered so I just closed the issue. 

I put the open graph tags in [`public/index.html`](https://github.com/adamalston/v2/blob/master/public/index.html) as a workaround although I would prefer to have them in my JavaScript files so that I can change them as needed. I looked around for other packages but was unable to find any.

**Comment by edolix** [comment]
I have the same issue. @adamalston did you solve this in the meantime? Thanks!

**Comment by adamalston** [comment]
@edolix I did not. Still using the workaround above: 

> I put the open graph tags in [`public/index.html`](https://github.com/adamalston/v2/blob/master/public/index.html) as a workaround although I would prefer to have them in my JavaScript files so that I can change them as needed. I looked around for other packages but was unable to find any.

**Comment by edolix** [comment]
Thanks @adamalston !

**Comment by ahsan-abrar** [comment]
I have the same issue.

**Comment by staylor** [comment]
you need SSR

**Comment by kaizenlabs** [comment]
> you need SSR

If the answer is SSR, then what is the point of using this library then? You can interpolate into index.html without using Helmet.
