### ISSUE TITLE
Duplicate description meta tag

### ISSUE THREAD

**Issue by advanceddev** [staylor/react-helmet-async#108]
Hello there. I have default meta-tag **description** at the index.html
React-helmet can **replace meta-tag description** at the index.html, but not **react-helmet-async** 

### Now i have two meta-tag description: from index.html and from another page.

Usage:

_index.html_
`<meta name="description" content="My awesome description" data-react-helmet="true" />`

_anotherPage.js_
`<Helmet defer={false} titleTemplate="%s - My site" defaultTitle=My default title">`
`<title>Title for page</title>` - **work fine**
`<meta name="description" content="Another description" data-react-helmet="true" />` - **not working...**
 
But if i remove description tag from index.html, i don't see any description tag.

Remove `data-react-helmet="true"` didn't help.

P.s sorry for my English :)

**Comment by antoinegaillardpaloit** [comment]
A late solution here, in case anyone encounters the same problem: for react-helmet-async, the attribute to set is `data-rh="true"` instead of `data-react-helmet="true"`. It should really be documented, though 🤔

**Comment by slorber** [comment]
As @antoinegaillardpaloit said, using `data-rh="true"` on static meta tags work, but I noticed some important behavior to mention:

- Suppose you have this hardcoded meta in your HTML template: `<meta name="xyz" content="ABC" data-rh="true"/>`
- Now you render a React app but **don't** render this: `<Helmet><meta name="xyz" content="ABC" data-rh="true"/></Helmet>`
- Your SSR output will contain the `xyz` metadata
- **After hydration, the `xyz` metadata will be erased by Helmet**

**Comment by staylor** [comment]
> * Suppose you have this hardcoded meta in your HTML template: `<meta name="xyz" content="ABC" data-rh="true"/>`

add `data-rh="true"` to tags not rendered by Helmet probably voids your warranty

**Comment by Hat52** [comment]
I have tried these solution but still when I share a link to specific page of my site I get the meta tags that are defined in the index.html file. I am using CSR.

**Comment by heyalizaid** [comment]
I have a React project where the metadata is changing. But when I share my URL with someone, their title and description don't update. I have separate metadata for each page.

**Comment by Hat52** [comment]
> I have a React project where the metadata is changing. But when I share my URL with someone, their title and description don't update. I have separate metadata for each page.

I am facing similar issue.

**Comment by heyalizaid** [comment]
> > I have a React project where the metadata is changing. But when I share my URL with someone, their title and description don't update. I have separate metadata for each page.
> 
> I am facing similar issue.

Suggestions are to use NextJs SSR (Server Side Renderering) and also to use a separate system for this to preload pages. 
This is the article I am following to resolve this 
https://ravikirandhulipala.medium.com/how-to-resolve-meta-data-issues-in-react-spa-with-server-side-rendering-firebase-cloud-functions-7e5549690820

**Comment by Hat52** [comment]
> > > I have a React project where the metadata is changing. But when I share my URL with someone, their title and description don't update. I have separate metadata for each page.
> 
> > 
> 
> > I am facing similar issue.
> 
> 
> 
> Suggestions are to use NextJs SSR (Server Side Renderering) and also to use a separate system for this to preload pages. 
> 
> This is the article I am following to resolve this https://ravikirandhulipala.medium.com/how-to-resolve-meta-data-issues-in-react-spa-with-server-side-rendering-firebase-cloud-functions-7e5549690820

But I can use SSR

**Comment by EntitiCoder** [comment]
> > > > I have a React project where the metadata is changing. But when I share my URL with someone, their title and description don't update. I have separate metadata for each page.
> > 
> > 
> > > 
> > 
> > 
> > > I am facing similar issue.
> > 
> > 
> > Suggestions are to use NextJs SSR (Server Side Renderering) and also to use a separate system for this to preload pages.
> > This is the article I am following to resolve this https://ravikirandhulipala.medium.com/how-to-resolve-meta-data-issues-in-react-spa-with-server-side-rendering-firebase-cloud-functions-7e5549690820
> 
> But I can't use SSR [@heyalizaid](https://github.com/heyalizaid)

hi, im facing similar issue, have u fixed this?
