### ISSUE TITLE
Duplicate JSONLD

### ISSUE THREAD

**Issue by daydream05** [staylor/react-helmet-async#110]
So one of the packages that I use, [gatsby-plugin-next-seo](https://github.com/ifiokjr/gatsby-plugin-next-seo) uses this package under the hood and I think react-helmet-async is causing the duplicate jsonld.

When you inspect element the website, it only shows one, but using Google's Structured Data Testing Tool. It shows two.

Here's the codesandbox that replicates the issue:
https://codesandbox.io/s/duplicated-faq-rebfd

Deployed url:
https://csb-rebfd-omzyexojx.vercel.app/

Here's the structured data test where you can see it's duplicated:
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fcsb-rebfd-omzyexojx.vercel.app%2F

**Comment by rumbaa01** [comment]
@daydream05 hello, did you get the opportunity to solve this issue?

**Comment by daydream05** [comment]
@rumbaa01 so the problem was on google's side  if i remember correctly the way their tools works. I think it's fixed now.
