### ISSUE TITLE
canUseDOM heuristic is not a good one

### ISSUE THREAD

**Issue by joehoyle** [staylor/react-helmet-async#115]
While trying to get some stuff running in a custom v8 environment, this heuristic is giving a false-positive. How about using the same heuristic as React (at https://github.com/JedWatson/exenv/blob/master/index.js#L11-L15) which I think is a bit more robust?

https://github.com/staylor/react-helmet-async/blob/c7d3dcf38478b071467337e933de58dec0b951fe/src/Provider.js#L18

**Comment by staylor** [comment]
hello 3 years later! I am going to update this
