### ISSUE TITLE
Is it possible to disable `data-rh`?

### ISSUE THREAD

**Issue by chenxsan** [staylor/react-helmet-async#12]
I'm using reactjs as server side template, no rehydrate needed on the client side. So I think `data-rh` is useless then, would love to disable it.

**Comment by staylor** [comment]
ah I see - would be happy to look at a PR that does this

**Comment by chenxsan** [comment]
@staylor Sent a PR here https://github.com/staylor/react-helmet-async/pull/17.

**Comment by chenxsan** [comment]
Close it since I don't need it now.
