### ISSUE TITLE
componentWillMount will be removed in React 17.

### ISSUE THREAD

**Issue by chenxsan** [staylor/react-helmet-async#13]
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#gradual-migration-path, consider replacing it with `componentDidMount` here https://github.com/staylor/react-helmet-async/blob/fd149147d0d077fcf7417115433fcd4b406a7060/src/Dispatcher.js#L27?

**Comment by staylor** [comment]
see https://github.com/staylor/react-helmet-async/pull/7 - merged new Context API into master
