### ISSUE TITLE
prioritizeSeoTags prop in typescript

### ISSUE THREAD

**Issue by abolfazlharaini** [staylor/react-helmet-async#148]
Hello

Not declared prioritizeSeoTags prop in index.d.ts
Please add that prop to index.d.ts for using in typescript project

Thanks

**Comment by itsib** [comment]
Hey! 
You can add
`
declare module 'react-helmet-async' {
  export interface HelmetProps {
    prioritizeSeoTags?: boolean;
  }
}
`
in your **react-app-env.d.ts** file.
Read more [here](https://www.typescriptlang.org/docs/handbook/declaration-merging.html)

**Comment by abolfazlharaini** [comment]
I used that solution for my project
It would be better to add that type to the repository

Thanks a lot
