### ISSUE TITLE
Add children to HelmetProps for compatibility with React v18+

### ISSUE THREAD

**Issue by crates** [staylor/react-helmet-async#182]
Until you add this line into HelmetProps, anyone upgrading to version 18 of React will get the following error:
`Property children does not exist on type IntrinsicAttributes & ...`

Here's the line that needs to be added into "index.d.ts" to support React 18:

```
export interface HelmetProps {
...
children?: React.ReactNode;
...
}
```

Please fix this soon. We are having major issues without it.

**Comment by maurer2** [comment]
Hello, I believe the built in PropsWithChildren type could be used here

```ts
import type { PropsWithChildren } from 'react'

interface HelmetProps extends PropsWithChildren<{
    async?: boolean;
    base?: any;
    .....
}>
```

Cheers

**Comment by hnrchrdl** [comment]
As a temporary solution, this can be solved by extending the `HelmetProps` interface.

```js
// react-async-helmet.d.ts - create this file somewhere TS can pick it up.

declare module 'react-helmet-async' {
    export interface HelmetProps {
        children: ReactNode;
    }
}
```

**Comment by staylor** [comment]
https://github.com/staylor/react-helmet-async/pull/197
