### ISSUE TITLE
How to cleanup tags ?

### ISSUE THREAD

**Issue by dmitryshelomanov** [staylor/react-helmet-async#189]
I need to cleanup tags when page leaved. Can I do it ? By default tags not removed from dom

**Comment by josejulio** [comment]
They are cleaned for me - are you using `Helmet` in the both pages?

i.e. I have  this on my landing page
```
<Helmet>
    <title>My landing page</title>
</Helmet>
```

and this on other page:
```
<Helmet>
    <title>My other page</title>
    <meta name="the-tag-name" content="the-tag-content" />
</Helmet>
```

When I navigate from lading to "other page" the meta tags gets added - when i navigate to the landing page, the meta is removed.

**Comment by josejulio** [comment]
I believe so - there might be other ways but I don't know that much from this lib - sorry
