### ISSUE TITLE
React 18.2.0 + lazy 

### ISSUE THREAD

**Issue by YasKur** [staylor/react-helmet-async#190]
Hey, i updated to react: 18.2.0 and now react-helmet-async does not work. Alway show initial name page.
```
 const { title } = useLayoutTitle();
  return (
    <Suspense fallback={<Spinner isShow position='fixed' />}>
      <Helmet title={title} titleTemplate='%s' />
      <MainRoutes />
    </Suspense>
```
I get title from my redux store, title on page does not change, but react devtools have correct title, at props. 

When i remove lazy, it's work great, but with lazy it does not :(

**Comment by shellbryson** [comment]
Observation/related issue? This appears to be an issue with Lazy/Router. When navigating to a lazy component, the page title gets updated, but additional meta values are not set. Refreshing the page (forcing a full reload, via a regular hyperlink), everything works as expected.

**Comment by mcelikx** [comment]
I've this problem too. Did you find any way?

**Comment by shellbryson** [comment]
Sadly, I've not been able to find a fix.

**Comment by tazsingh** [comment]
I've moved to use https://github.com/0no-co/hoofd by @jovidecroock and it's been working great for us!

**Comment by shellbryson** [comment]
That looks good @tazsingh, thanks for sharing. I'll take a look later today.

**Comment by YasKur** [comment]
For my simple task, i create small hook:
```
import { useEffect } from 'react';

/**
 * @export
 * @param {string} [title=Main]
 */

export const useSetDocumentTitle = (title: string) => {
  useEffect(() => {
    document.title = title;
  }, [title]);
};
```

@tazsingh thanks for sharing <3

**Comment by A6Brgeuka** [comment]
[hoofd](https://github.com/0no-co/hoofd) works great! but it doesn't support the prioritization.

**Comment by JoviDeCroock** [comment]
@A6Brgeuka you can always implement this in the repository but even more important... You can just categorize these yourself as [`toStatic`](https://github.com/0no-co/hoofd?tab=readme-ov-file#ssr) offers you everything you need.
