### ISSUE TITLE
Favicon not updating on Google Chrome but working fine on Mozilla Firefox

### ISSUE THREAD

**Issue by maaz-munir** [staylor/react-helmet-async#195]
I checked on Edge as well and it has the same issue. Is it an issue with caching on chromium based browsers?

**Comment by fdemian** [comment]
Hi! I'm having the same problem on chromium with the latest version as of this writing (version 2.0.3).

**Comment by fdemian** [comment]
@maaz-munir looks like adding `data-react-helmet="true"` to the favicon solves this isssue (at least for me). 
Something like this

`    <link rel="icon" type="image/svg+xml" href="/vite.svg" data-react-helmet="true" />
`

**Comment by maaz-munir** [comment]
thanks @fdemian I think i did try something like that but didnt work for me. So I just did a workaround and changed the favicon with a useEffect on the inital page load
