### ISSUE TITLE
preview url not working

### ISSUE THREAD

**Issue by sam4rano** [staylor/react-helmet-async#196]
Sharing link to socials does not seems to reveal image and other meta informations, using react

**Comment by ameyer117** [comment]
That is a side effect of a client-side single-page-application. This package cannot do anything to help with that. I'd suggest reading [this article](https://stackoverflow.blog/2021/12/28/what-i-wish-i-had-known-about-single-page-applications#h2-086d2da63fb40) to understand why that's the case.
