### ISSUE TITLE
Optional Context break in 0.2.0

### ISSUE THREAD

**Issue by eMerzh** [staylor/react-helmet-async#199]
Hello @staylor 

Thanks for maintaining this 🎉 
It's me or the latest version breaks when you try to instantiate an HelmetProvider without context ? 
```jsx
	<HelmetProvider>
	<Other>
	<Helmet  title="yasss" />
	</Other>
      	</HelmetProvider>
```
much like in the example in the readme? 
probably making the context optional in types should do it?

**Comment by staylor** [comment]
2.0.1 is published - thanks! https://www.npmjs.com/package/react-helmet-async?activeTab=versions

**Comment by eMerzh** [comment]
awesome! thanks for the quick fix 🙏
