### ISSUE TITLE
Do Fragments work?

### ISSUE THREAD

**Issue by aendrew** [staylor/react-helmet-async#20]
This package seems to have the same issue as the original `react-helmet`, insomuch that it doesn't see `<Fragment>` as a valid tag and the check [on line 143 in index.js](https://github.com/staylor/react-helmet-async/blob/9ccb8c0425ecc253272e420cf2d92d2b9beb2cbf/src/index.js#L143) sees the `<Fragment>` as a function (given it's actually a proxy, AFAICT?). 

I may be totally wrong about this however and would absolutely love to be proven wrong. 😄

**Comment by staylor** [comment]
I opened a PR to add support for `<Fragment>`

**Comment by oyeanuj** [comment]
@staylor I'm still seeing errors with `Fragment`. The following code doesn't seem to work:

```jsx
render () {
	return (
		<Helmet>
			{
				title &&
				<Fragment>
					<meta name = "title"			content = { title } />
					<meta name = "twitter:title"	content = { title } />
					<meta property = "og:title"		content = { title } />
				</Fragment>
			}
			{
				description &&
				<Fragment>
					<meta name = "description"			content = { description } />
					<meta name = "twitter:description"	content = { description } />
					<meta property = "og:description"	content = { description } />
				</Fragment>
			}
		</Helmet>
	)
}
```

Any ideas what might be going on?

**Comment by nathggns** [comment]
@oyeanuj did you ever figure this out? I'm still experiencing this problem.
