### ISSUE TITLE
TypeError: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by chenxsan** [staylor/react-helmet-async#27]
So I tested my code after https://github.com/staylor/react-helmet-async/pull/25 was merged. Unfortunately, the problem still exists because two different probjects are consuming two different `Provider` modules, i.e., two different `Context` exported in `Provider`. So that pull request didn't fix the real problem.

**Comment by koulmomo** [comment]
The real fix is what staylor commented here: https://github.com/staylor/react-helmet-async/pull/25#issuecomment-418415273

Assuming you have:

Main Project -> `app`
Subproject Foo -> `Foo`
Subproject Bar -> `Bar`

In the package.json for `Foo` + `Bar`, **REMOVE** `react-helmet-async` from their dependencies and:

1) Add it to `peerDependencies`
2) Add it to `devDependencies`
3) Make sure the `peerDependencies` for `Foo` + `Bar` overlap. Ideally they should be the same

in `app`, add `react-helmet-async` as a `dependency` that satisfies the `peerDependencies` for `Foo` + `Bar`

Now if you run `npm install`/`yarn` in `app`, it should only download **ONE** version of `react-helmet-async`

**Comment by DevanB** [comment]
@chenxsan thanks for the heads up. I was following it so closely because I already tried the fixes in the PR and it didn’t resolve the issue, but I had a hope that maybe I did something incorrectly.

**Comment by chenxsan** [comment]
@koulmomo I just thought that If we could fix it in `react-helmet-async`, it will improve our developer experience a lot :).

**Comment by staylor** [comment]
I am going to close this - the official answer is to use peerDeps, which is what we do at the New York Times. See this comment for explanation: https://github.com/staylor/react-helmet-async/issues/27#issuecomment-422612330

**Comment by KasparRosin** [comment]
I followed this example https://github.com/staylor/react-helmet-async/issues/27#issuecomment-422612330 but am still running into this issue. 

TypeError: Cannot read property 'add' of undefined

If i manually go into node_modules folder and symlink the react-helmet-async package it works. This is a problem while developing locally and having the subproject linked/installed from a sibling folder (`npm install ../subproject`).
