### ISSUE TITLE
version 0.2 is not compatible with react-router

### ISSUE THREAD

**Issue by seeden** [staylor/react-helmet-async#28]
I have tried version 0.2 from alpha to beta.1 but I can see always next issue related somehow to react-router.
```js
Uncaught (in promise) TypeError: Cannot read property 'router' of undefined
    at ProxyComponent.getChildContext (app.js:127634)
    at ProxyComponent.getChildContext (app.js:123532)
```

**Comment by staylor** [comment]
can you reproduce with a CodeSandbox?

**Comment by tp** [comment]
I can just provide anecdotal data, but I haven't seen any issue with `react-helmet-async` when switching to it in our application (from `react-helmet`).

We're using `react-router` `4.3.1`.
