### ISSUE TITLE
Incorrect dist-tag for react-helmet-async@latest

### ISSUE THREAD

**Issue by KevinGrandon** [staylor/react-helmet-async#30]
Just wanted to let you know that the `latest` dist-tag for react-helmet-async is currently incorrect. It points to `0.2.0-beta.1`, which it should probably point to `0.1.0`. This will result in folks upgrading to the beta version automatically, which they should probably stay on the 0.1.x branch.

**Comment by staylor** [comment]
my mistake! I just bumped to `0.2.0`, will correct the workflow for next time
