### ISSUE TITLE
React 16.6.0 bug

### ISSUE THREAD

**Issue by dlebedynskyi** [staylor/react-helmet-async#32]
There seems to be an  issue with react 16.6.0 -1  context api on server side render 

getting following errors during render 
```
Warning: Rendering <Context.Consumer.Provider> is not supported and will be removed in a future major release. Did you mean to render <Context.Provider> instead?
Warning: Rendering <Context.Consumer.Consumer> is not supported and will be removed in a future major release. Did you mean to render <Context.Consumer> instead?
Warning: Failed prop type: The prop `context` is marked as required in `Dispatcher`, but its value is `undefined`.
    in Dispatcher

```
TypeError: Cannot read property 'helmetInstances' of undefined

  - Dispatcher.js:70 Dispatcher.init
    [id-portal-web]/[react-helmet-async]/lib/Dispatcher.js:70:48

  - Dispatcher.js:116 Dispatcher.render
    [id-portal-web]/[react-helmet-async]/lib/Dispatcher.js:116:12
```
this seems to be happening because  of context consumer is initialized on first run with null values 
```
return _react2.default.createElement(
        _Provider.Context.Consumer,
        null,
        function (context) {
 // 👇 here 
          return _react2.default.createElement(_Dispatcher2.default, _extends({}, newProps, { context: context }));
        }
      );
```

I had similar issues on other Context using packages with server sider render.

**Comment by dlebedynskyi** [comment]
after additional investigation, I found that problem is actually in react-async-component. Closing PR as not relevant

**Comment by mschipperheyn** [comment]
@dlebedynskyi Any suggestions on how you fixed the issue? Running into it myself

**Comment by dlebedynskyi** [comment]
I just ripped off react-async-component and replaced with https://github.com/smooth-code/loadable-components. 

Core issues for me was null passed to provider on SSR. that was a bug in react-async-component.

**Comment by mschipperheyn** [comment]
I did the same and I still have the same error :-( 

The error is caused I think by `react-async-bootstrapper`

**Comment by mschipperheyn** [comment]
You should reference https://github.com/ctrlplusb/react-async-bootstrapper/issues/14

**Comment by aseem2625** [comment]
**Similar issue:**
I tried integrating with [repo](https://github.com/workco/marvin) and development built is working fine, however, while serving the production built app, throws at server itself.

```
Warning: Failed prop type: The prop `context` is marked as required in `Dispatcher`, but its value is `undefined`.
    in Dispatcher
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'helmetInstances' of undefined

```

**Comment by kishankanugula** [comment]
@aseem2625 I am also facing the same issue. Did you find any solution? Thank you for any help.
