### ISSUE TITLE
Helmet tag not being updated in production with server rendering

### ISSUE THREAD

**Issue by oyeanuj** [staylor/react-helmet-async#37]
HI @staylor! While implementing this library with server rendering, I am noticing that while the updated tags show up in the server-rendered code in development, they do not do show up in production.

Here is my code on the server side. Specifically `helmetContext.helmet.meta.toString` shows up as empty in production while it works perfectly fine in development. I'm on React 16.5.2, Webpack 4.16 and Node 10.

```jsx
// Holds Helmet state specific to each request
const helmetContext = {}

// Declare our React application.
const app = (
  <AsyncComponentProvider asyncContext = { asyncComponentsContext }>
    <JobProvider jobContext = { jobContext }>
      <StaticRouter location = { request.url } context = { reactRouterContext }>
        <HelmetProvider context = { helmetContext } >
          <Provider store = { store }>
            <CookiesProvider cookies = { request.universalCookies }>
              <UserAgentProvider ua = {request.headers["user-agent"]} >
                  <IntlProvider
                    locale		= { locale }
                    messages	= { messages }
                    initialNow	= { Date.now() }
                    textComponent = { Fragment }
                  >
                    <Route component = { App } />
                  </IntlProvider>
              </UserAgentProvider>
            </CookiesProvider>
          </Provider>
        </HelmetProvider>
      </StaticRouter>
    </JobProvider>
  </AsyncComponentProvider>
)

// ℹ️ First we bootstrap our app to ensure the async components/data are resolved
await asyncBootstrapper( app )

const jsx = sheet.collectStyles( app )
const stream = sheet.interleaveWithNodeStream(
  renderToNodeStream( jsx ),
)

// Resolve the assets (js/css) for the client bundle's entry chunk.
const clientEntryAssets = getClientBundleEntryAssets()

const { helmet } = helmetContext

/*
* all of the things in the params below are included in the header
* can add htmlAttributes & bodyAttributes from Helmet if needed
*/
const paramsForHeader = {
  titleTag:	helmet.title.toString(),
  metaTags:	helmet.meta.toString(),
  linkTags:	helmet.link.toString(),
  cssBundle:	clientEntryAssets && clientEntryAssets.css,
  nonce,
}

console.log( "metaTags toString:", helmet.meta.toString())  // nothing
console.log( "metaTags toComponent", helmet.meta.toComponent()) // nothing either

/*
* all of the things in the params below are included in the footer
*/
const paramsForFooter = {
  storeState:	store.getState(),
  routerState: reactRouterContext,
  jobsState:	jobContext.getState(),
  asyncComponentsState:	asyncComponentsContext.getState(),
  jsBundle:		clientEntryAssets.js,
  clientConfig,
  polyfillPath,
  nonce,
}

switch ( reactRouterContext.status ) {
  case 301:
  case 302:
  // ...
      break

  case 404:
  // ...
      break

  default:
      // Otherwise everything is all good and we send a 200 OK status.
      response.status( 200 )
      response.type( "html" )
      response.setHeader( "Cache-Control", "no-cache" )
      response.write( Head( paramsForHeader ))
      stream.pipe( response, { end: false })
      stream.on( "end", () => response.end( Footer( paramsForFooter )))
}

```

Any ideas what might be going on?

**Comment by oyeanuj** [comment]
@staylor I noticed that what seems to be happening is that the render method of the child component in the tree which has the meta tags hasn't been invoked in time for the call to `helmet.meta.toString()` above.

Do you think race conditions are a possible reason? Or is there another way to structure it to ensure that RHA has gone thru the tree and traversed the render of all child components?

**Comment by darkowic** [comment]
I have similar issue that I detect on production
Template:
```
<head>
  ${helmet.title.toString()}
  ${helmet.meta.toString()}
  ${helmet.link.toString()}
  ${helmet.script.toString()}  
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
```
Result:
```
<head>
--
<title data-rh="true"></title>
// here supposed to be data from react helmet


<meta http-equiv="X-UA-Compatible" content="IE=edge" />
```

Problem is that I can not reproduce it. It happened on few pages only. I can see it because my pages are cached

**Comment by wmertens** [comment]
@oyeanuj are you streaming? Check out #3

**Comment by reduxdj** [comment]
I am having the exact same issue, working from the minimal example on React 16.8.2 and node 9.6.
This happens every time I try to use it

**Comment by titchimoto** [comment]
Just checking if there were any updates on this, I am currently having a similar issue. Any of my helmet tags are always empty.

`<title data-rh="true"></title>`

**Comment by reduxdj** [comment]
Looks like the main contributor of this app isn't really active... thanks for putting this out here... It would be great if you engaged with some of your followers here @staylor

**Comment by diondirza** [comment]
The problem is it is a stream, and it is async process. the moment your read the variable the stream is not done for read yet. Therefore you need to attach event `on('end', cb)` on this stream, so you could see the value. See my sample implementation here.

```
      const bodyStream = renderToNodeStream(app);
      const transformStream = new CustomTransform(); // this transfrom needed to do clever stream concatenation

      bodyStream.pipe(
        transformStream,
        { end: false },
      );
      bodyStream.on('end', () => {
        const htmlStates = {
          htmlStates,
          helmet: helmetContext.helmet,
        };
        // at this point you can see your helmetContext.helmet has filled 
        const [header, footer] = htmlTemplate(htmlStates);

        transformStream.write(header);
        transformStream.end(footer);
      });
      reply.send(transformStream);
```

As you can see we pipe body, then write head and footer because we need to process body first. That's why we need to use transform stream to flip it back to proper order.

**Comment by Buddikazz** [comment]
@diondirza please explain on this where to apply

**Comment by diondirza** [comment]
Apply this on your server code.

**Comment by Buddikazz** [comment]
@diondirza please share your server code

**Comment by devcat22** [comment]
@titchimoto did you resolve it? I've been battling the same thing for a few days now. I cannot figure out why it's empty.

**Comment by staylor** [comment]
streaming is not officially supported - the only time I can “recommend” using it is if you already did a full render via something like Apollo, helmetContext is already populated, and your head HTML is SSR’d outside of the React streaming render. I am open to PRs that address it

at the NYT, we don’t use streaming because our end users are not hitting our application servers directly - our Node servers are behind nginx and then Fastly.

**Comment by staylor** [comment]
Streaming remains experimental with this library, open to PRs or docs that add more support. Even Next is wrestling with how to do this

**Comment by jee** [comment]
@diondirza interesting solution, though wouldnt waiting for the 'end' event to write the header and footer negatively affect performance and negate the benefit of streaming?

**Comment by diondirza** [comment]
@jee good question, so far what I have seen it is not negate all benefits from it. You probably realized in the above code we didn't send any byte to response stream yet until the body fully read, even though we already open a connection to the client but it receives nothing. The solution you could do is to have some static header before dynamic one and send it to stream immediately, so it will be counted as the first byte.
