### ISSUE TITLE
Typescript: TS2304: Cannot find name 'React'.

### ISSUE THREAD

**Issue by yowakita** [staylor/react-helmet-async#40]
When I try to do a server build using react-helmet-async,  I get the aforementioned Typescript error. Shouldn't React be imported if React.Component is being used?
https://github.com/staylor/react-helmet-async/blob/master/index.d.ts#L13

I could create a PR if that is necessary- I'm not sure if I'm misunderstanding how types work, I'm relatively new to Typescript. Thanks!

**Comment by staylor** [comment]
yes, this needs a PR

**Comment by yowakita** [comment]
thank you @staylor , I created a pull request for this.

**Comment by yowakita** [comment]
I saw that the PR was merged, thank you @staylor. Closing this issue now.
