### ISSUE TITLE
Don't include server.js on the client

### ISSUE THREAD

**Issue by mxstbr** [staylor/react-helmet-async#6]
Looking at my bundle analyzer I see this:

![screen shot 2018-02-20 at 13 51 30](https://user-images.githubusercontent.com/7525670/36424916-4de705ee-1645-11e8-96da-4893d84a3646.png)

Looks like `server.js` is included in the browser. Is that needed?

**Comment by staylor** [comment]
maybe not, will look

**Comment by mxstbr** [comment]
Just stumbled upon this again, was this ever resolved @staylor?

**Comment by staylor** [comment]
I am going to attack this via https://github.com/staylor/react-helmet-async/pull/42 - will push a beta soon and test on NYT. Part of the size problem was that I wasn't transforming the Babel runtime. I'd rather make the build small using `microbundle` than churn a ton of code

**Comment by staylor** [comment]
everything is packaged with `microbundle` since https://github.com/staylor/react-helmet-async/commit/cc8eb42efb8cbbe71914e3e857a3e3a8ef638a25
