### ISSUE TITLE
Add looser peer dep requirements for react and react-dom?

### ISSUE THREAD

**Issue by majapw** [staylor/react-helmet-async#60]
QQ: Would it be possible to loosen the `react` and `react-dom` peer dep restrictions to `^16.0.0` or are there explicit dependencies on react 16.6+ features in this library?

**Comment by macklinu** [comment]
I'm seeing a usage of `React.createContext`, which was [introduced in React 16.3.0](https://reactjs.org/blog/2018/03/29/react-v-16-3.html), so unless that was polyfilled, I'm not sure the peer dep restrictions can currently be loosened to `^16.0.0`.

https://github.com/staylor/react-helmet-async/blob/463b603fcc5f4dbeabc560659709223881f5ac2b/src/Provider.js#L7
