### ISSUE TITLE
Expand TypeScript definitions

### ISSUE THREAD

**Issue by davidje13** [staylor/react-helmet-async#61]
`index.d.ts` offers very basic type information for this package, but misses some properties.

I am setting `HelmetProvider.canUseDOM = false` (see #41), but `canUseDOM` isn't defined.

For now, I am working around this by adding my own definitions on top:

```ts
declare module 'react-helmet-async' {
  namespace HelmetProvider {
    var canUseDOM: boolean;
  }
}
```

But this should be fixed at the source. You can add a namespace (as above) or just put a static property on the class which is already exported. Also as noted by #38, since this depends on `@types/react-helmet`, that should be listed as a dependency of this project.

**Comment by ekilah** [comment]
yeah https://github.com/staylor/react-helmet-async/blob/7a7394742b8fbe6586d9daaa3bfff28a89cc9e83/index.d.ts#L3 shouldn't really be here, seems like the types from `@types/react-helmet` should be copied over.

**Comment by JakeGinnivan** [comment]
I was hoping to use TypeScript to see where my helmet usage was broken, but due to the re-exported types invalid API calls like `.rewind()` are invalid.

+1 on the copying the types over to be able to resolve issues like this. Happy to put together a PR if you agree @staylor
