### ISSUE TITLE
empty title tags when rendering component

### ISSUE THREAD

**Issue by devcat22** [staylor/react-helmet-async#80]
Hello!

I'm trying to swap out my usage from `react-helmet` to use `react-helmet-async`, but I am noticing that my title tags are empty every single time.

Here's how what I'm doing it:

## On the client, the component to be rendered.
```
        <HelmetProvider>
            <Helmet>
                <title>Hello</title>
            </Helmet>
        </HelmetProvider>
```

## On the server
```
const withHelmetProvider = (Component, context) => ({ ...props }) => (
    <HelmetProvider context={context}>
        <Component {...props} />
    </HelmetProvider>
);

const helmetContext = {};
ReactDOM.renderToString(withHelmetProvider(Component, helmetContext));
const { helmet } = helmetContext;
console.log(helmet.title.toStringI());
```

I see that every time the server logs, the tag is empty:
```
<title data-rh="true"></title>
```

What are some possible causes for this? I've verified the following:
- The client and server are using the same version of react-helmet-async (^1.0.4)
- The HelmetProvider is high enough, the component really just that!

I wanted to ask what could be some common causes for it? 

I've made sure that the helmetContext is living for the entire lifecycle of the request.

**Comment by devcat22** [comment]
On the note of debugging, I think microbundle was a poor choice to use as a build tool.

microbundle seems to be designed for libraries to that are supposed to be shipped down to the browser **only**. This library is used on both the server and the browser.

Unfortunately, you can't even build a non minified version of the source for quick debugging. You have to fork, make changes to microbundle to not compress the file and then link it back to the package.

**Comment by devcat22** [comment]
So it looks like while it's rendering on the server (during renderToString), it does recognize the tags, after applying more logs:

```
**** state to map onto server ****
{ baseTag: [],
  bodyAttributes: {},
  defer: true,
  encode: true,
  htmlAttributes: {},
  linkTags: [],
  metaTags: [],
  noscriptTags: [],
  onChangeClientState: [Function],
  scriptTags: [],
  styleTags: [],
  title: 'Hello',
  titleAttributes: {} }
```

Just can't tell why the helmet instance on the context object is always empty.

**Comment by devcat22** [comment]
Sigh. Even the initial release doesn't work. I'm not sure what's going on here. @staylor (or anyone?) are there any clues as to what could be the issue?

**Comment by staylor** [comment]
what version of React?

**Comment by devcat22** [comment]
React is at `16.12.0`.

**Comment by devcat22** [comment]
So I'm finding that it only works if the render to string directly has a Helmet tag.

This example works fine.
```
        const helmetContext = {};
        const Component = components[componentName];
        ReactDOM.renderToString(
            <HelmetProvider context={helmetContext}>
                <Helmet>
                    <title>Hello 2</title>
                </Helmet>
                <Component {...props}/>
            </HelmetProvider>
        );
        const { helmet } = helmetContext;
        console.log(helmet.title.toString()); // logs <title data-rh="true">Hello 2</title>
```

But when `Component` has the tag, it's able to find it.. but it's empty in context.

**Comment by devcat22** [comment]
Ok, I think see what the issue is.. it looks like if `Component` has `HelmetProvider`, it'll be empty on the server

```
// component.js -- doesn't work, logs empty title, <title data-rh="true"></title>
export default (props: Props) => (
    <HelmetProvider>
        <Helmet>
            <title>yo this is a cool title</title>
        </Helmet>
    </HelmetProvider>
);
```

But if it just has Helmet, it's able to log it out fine, as expected.

```
// component.js -- works fine
export default (props: Props) => (
        <Helmet>
            <title>yo this is a cool title</title>
        </Helmet>
);
```

**Comment by devcat22** [comment]
Going to close out this issue. It looks like the problem was two Providers competing with each other.
