### ISSUE TITLE
Consider keeping a changelog and publishing git tags for releases

### ISSUE THREAD

**Issue by shepmaster** [staylor/react-helmet-async#93]
1.0.5 appears to have been released, but it's difficult to see exactly what changed without either of these artifacts. It *appears* to be [this diff](https://github.com/staylor/react-helmet-async/compare/e02564f41b9e69360789f30352c3388094107cb3...fdde6855c9f260f2c1b5cda11c7c861c40359767).

**Comment by JakeGinnivan** [comment]
I can highly recommend https://www.npmjs.com/package/@changesets/cli

It's been working great for my projects

**Comment by staylor** [comment]
yeah I have been horrible about this - would someone like to propose these changes in a PR?

**Comment by JakeGinnivan** [comment]
I’ll put up a PR today with the setup I have on my projects, I love it.
________________________________

**Comment by mattlubner** [comment]
It's worth considering using an automated release tool such as [semantic-release](https://github.com/semantic-release/semantic-release), and moving the process of versioning and publishing to CI. This is how a number of popular OSS packages handle their versioning.

The really nice part is that semantic-release compiles release notes for every distinct version it publishes (based on git commit messages), and also handles the actual npm publishing, and git tag/release creation.

**Comment by staylor** [comment]
https://github.com/staylor/react-helmet-async/commit/3054564365a0881b934abb2d9e016fd4ab4d57fe

**Comment by shepmaster** [comment]
You've closed this, but I don't see any git tags or GitHub releases for 1.0.7, and I still don't see a changelog or equivalent.

**Comment by shepmaster** [comment]
1.0.6 to 1.0.7 *appears* to be [this diff](https://github.com/staylor/react-helmet-async/compare/51ce106a4b2eee1ec1cdb46034eba692fcd8f5cc..c4f941450ad2a3417039488ce5a9193fe941e98e).

**Comment by natterstefan** [comment]
Hi @staylor, please consider adding a CHANGELOG.md or make use of [GitHub's release feature](https://github.com/staylor/react-helmet-async/releases). This would be very helpful to users of your lib. Thanks a lot. Enjoy your day.
