### ISSUE TITLE
Unit testing functional components rendering Helmet.

### ISSUE THREAD

**Issue by Midhun-Carousell** [staylor/react-helmet-async#99]
Hi,I recently ran in to an issue while unit testing functional components rendering meta tags using Helmet.

A snippet of my code:
````
const myComponent=()=>{
      // I use selectors from redux to access some information
      return (
      <Helmet
        title="title"
        meta={[{name="description",content="xyz"}]}
        link={[{ href: getCanonicalUrl(), rel: "canonical" }]}
      />
  );
 }
 export default myComponent;
````

The unit test for the above component was executed using jest and enzyme however it always failed with an exception
````
console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [TypeError: Cannot read property 'add' of undefined]
        at reportException
The above error occurred in the <HelmetDispatcher> component:
        in HelmetDispatcher (created by Context.Consumer)
.....
````
My unit tests used the mount method of enzyme:

````
// connect the component with some mock store values
const wrapper = mount(
            <Provider store={store}>
                <myComponent {...mockProps}  />
            </Provider>,
    );
````
We had written countless unit tests before for Helmet but they were all class components.

Why did I have to encapsulate my component in <HelmetProvider> to unit test the above functional component?It took a lot of time to figure that i have to encapsulate so.But why?

**Comment by cyberSane** [comment]
@Midhun-Carousell , I ran into the same problem, the one thing which was missing in the test cases was I was not wrapping my component with HelmetProvider imported from react-helmet-async. internally Helmet consume Context so it expected the context provider from the parent component.

For me below code worked fine:
```
import {HelmetProvider} from "react-helmet-async";

const wrapper = mount(
             // redux Provider
            <Provider store={store}>
                  // helmet Provider
                <HelmetProvider>
                   <myComponent {...mockProps}  />
               </HelmetProvider>
            </Provider>
    );

```

**Comment by Uttu316** [comment]
I am still getting this issue
